### ISSUE TITLE
`tbl_start` should allow users to specify default functions for `summary`.

### ISSUE THREAD

**Issue by thomasgstewart** [thomasgstewart/tangram.pipe#5]
Perhaps a feature to think about as time allows.

Not sure how hard it is to do this.

Basic idea is that 

```
tbl_start(
    col_var = "x"
  , num_summary = my_custom_function
  , cat_summary = another custom function
```

**Comment by guidean** [comment]
`tbl_start` has been updated to include default functions for numeric, categorical, and binary data.
